kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aapm-sidecar-injector
  labels:
    app: aapm-sidecar-injector
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
