apiVersion: v1
kind: ConfigMap
metadata:
  name: aapm-sidecar-injector
  labels:
    app: aapm-sidecar-injector
data:
  sidecarconfig.yaml: |
    containers:
    - name: aapm-client 
      image: krontechnology/aapm-client:1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
       - name: keystore 
         mountPath: /keystore
    volumes:
       - name: keystore
         configMap:
                name: aapm-configmap
