apiVersion: v1
kind: Service
metadata:
  name: aapm-sidecar-injector
  labels:
    app: aapm-sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: aapm-sidecar-injector
