apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kron-aapm-sidecar.fullname" . }}
  labels:
    app: {{ include "kron-aapm-sidecar.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "kron-aapm-sidecar.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kron-aapm-sidecar.fullname" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - -service-name=aapm-sidecar-injector
          - -sidecar-config-file=/etc/webhook/config/sidecarconfig.yaml
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/prestop.sh"]
          volumeMounts:
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-config
        configMap:
          name: aapm-sidecar-injector

