apiVersion: v1
kind: Secret
metadata:
  name: aapm-client-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  AGENT_SERVICE: {{ required "aapmConnection.agentService is required" .Values.aapmConnection.agentService | quote }}
  AGENT_PORT: {{ required "aapmConnection.agentPort is required" .Values.aapmConnection.agentPort | toString | quote }}
  DIRECT_ACCESS_URL: {{ required "aapmConnection.directAccessUrl is required" .Values.aapmConnection.directAccessUrl | quote }}
  application-aapm-client.yml: |
    aapm:
      client:
        poll-interval-ms: {{ .Values.aapmClient.pollIntervalMs | default 30000 }}
        secrets:
        {{- range .Values.aapmClient.secrets }}
          - userLabel: {{ .userLabel | quote }}
            secret: {{ .secret | quote }}
            token: {{ .token | quote }}
            accPath: {{ .accPath | quote }}
        {{- end }}
