apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aapm-sidecar-injector
  name: aapm-sidecar-injector
  namespace: aapm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aapm-sidecar-injector
  template:
    metadata:
      labels:
        app: aapm-sidecar-injector
    spec:
      containers:
      - args:
        - -service-name=aapm-sidecar-injector
        - -sidecar-config-file=/etc/webhook/config/sidecarconfig.yaml
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: krontechnology/aapm-sidecar-injector:1.1.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /prestop.sh
        name: aapm-sidecar-injector
        volumeMounts:
        - mountPath: /etc/webhook/config
          name: webhook-config
      serviceAccountName: aapm-sidecar-injector
      volumes:
      - configMap:
          name: aapm-sidecar-injector
        name: webhook-config
