apiVersion: v1
kind: Service
metadata:
  labels:
    app: aapm-sidecar-injector
  name: aapm-sidecar-injector
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: aapm-sidecar-injector
