apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aapm-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aapm-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aapm-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aapm-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aapm-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AGENT_SERVICE
              value: {{ .Values.agent.service | quote }}
            - name: AGENT_PORT
              value: {{ .Values.agent.port | quote }}
            - name: DIRECT_ACCESS_URL
              value: {{ .Values.pam.url | quote }}
            - name: SSL_ENABLED
              value: {{ .Values.tls.enabled | quote }}
            - name: KEYSTORE_PATH
              value: {{ .Values.tls.keystorePath | quote }}
            - name: KEYSTORE_PASSWORD
              value: {{ .Values.tls.password | quote }}
            - name: KEYSTORE_ALIAS
              value: {{ .Values.tls.keyAlias | quote }}
            - name: DISABLE_AGENT_SECURE_CHANNEL
              value: {{ .Values.agent.disableSecureChannel | quote }}
            - name: IGNORE_AGENT_CERTIFICATE
              value: {{ .Values.agent.ignoreCertificate | quote }}
            - name: DISABLE_INTERCEPTOR_SECURE_REQUEST
              value: {{ .Values.interceptor.disableSecureRequest | quote }}
            - name: IGNORE_INTERCEPTOR_CERTIFICATE
              value: {{ .Values.interceptor.ignoreCertificate | quote }}
            - name: KEYSTORE_DIR
              value: {{ .Values.client.keystoreDir | quote }}
            {{- range $i, $user := .Values.client.users }}
            - name: AAPM_CLIENT_SECRETS_{{ $i }}_USER_LABEL
              value: {{ $user.label | quote }}
            - name: AAPM_CLIENT_SECRETS_{{ $i }}_ACC_PATH
              value: {{ $user.accPath | quote }}
            - name: AAPM_CLIENT_SECRETS_{{ $i }}_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.clientCredentials.secretName }}
                  key: {{ $user.secretKey }}
            - name: AAPM_CLIENT_SECRETS_{{ $i }}_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.clientCredentials.secretName }}
                  key: {{ $user.tokenKey }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.tls.enabled }}
          volumeMounts:
            - name: tls-keystore
              mountPath: /etc/tls
              subPath: keystore.p12
          {{- end }}
      {{- if .Values.tls.enabled }}
      volumes:
        - name: tls-keystore
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
