apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kron-aapm-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kron-aapm-agent.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "kron-aapm-agent.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "kron-aapm-agent.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: SINGLECONNECT_INSTALLTOKEN
              valueFrom:
                secretKeyRef:
                  key: installToken
                  name: {{ .Values.secrets.name }}
            - name: PAM_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: address
                  name: {{ .Values.secrets.name }}
            - name: PAM_FAILOVER_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: failoverAddress
                  name: {{ .Values.secrets.name }}
            - name: SINGLECONNECT_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystorePassword
                  name: {{ .Values.secrets.name }}
            - name: GRPC_PORT
              value: {{ .Values.config.grpc.port | quote }}
            - name: SINGLECONNECT_PROTOCOL
              value: {{ .Values.config.singleconnect.protocol | quote }}
            - name: AGENT_NAME
              value: {{ .Values.config.singleconnect.agentName | quote }}
            - name: HTTP_SSL_IGNORED
              value: {{ .Values.config.singleconnect.sslIgnored | quote }}
            - name: HTTP_HOSTNAME_IGNORED
              value: {{ .Values.config.singleconnect.hostnameIgnored | quote }}
            - name: PASSWORD_CHECK_PERIOD_REGULAR
              value: {{ .Values.config.password.statusCheck.regular | quote }}
            - name: PASSWORD_CHECK_PERIOD_INTENSIVE
              value: {{ .Values.config.password.statusCheck.intensive | quote }}
            - name: PASSWORD_CHECK_PERIOD_BUFFER
              value: {{ .Values.config.password.statusCheck.bufferInSeconds | quote }}
            - name: PASSWORD_CHECK_PERIOD_GRACE
              value: {{ .Values.config.password.statusCheck.graceInMinutes | quote }}
            - name: TOOLS_AUTHENTICATION
              value: {{ .Values.config.tools.authentication | quote }}
            - name: SYSTEM_SERVICE_MODE
              value: {{ .Values.config.system.serviceMode | quote }}
            - name: APP_IP_ADDRESS
              value: {{ .Values.config.app.ipAddress | quote }}
            - name: GRPC_SECURITY_ENABLED
              value: {{ .Values.config.app.grpc.security.enabled | quote }}
            - name: GRPC_TLS_PROTOCOLS
              value: {{ .Values.config.app.grpc.security.protocols | quote }}
            - name: GRPC_TLS_CIPHERS
              value: {{ .Values.config.app.grpc.security.ciphers | quote }}
            - name: APP_GRPC_SECURITY_DIST_CERT_CHAIN
              value: {{ .Values.config.app.grpc.security.dist.certChain | quote }}
            - name: APP_GRPC_SECURITY_DIST_PRIVATE_KEY
              value: {{ .Values.config.app.grpc.security.dist.privateKey | quote }}
            - name: MACHINE_ID
              value: {{ .Values.config.machineId | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
