apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ include "kron-aapm-agent.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "kron-aapm-agent.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "kron-aapm-agent.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:          
            - name: singleconnect.installToken
              valueFrom:
                secretKeyRef:
                  key:  installToken
                  name: {{ .Values.secrets.name }}
            - name: singleconnect.address
              valueFrom:
                secretKeyRef:
                  key:  address
                  name: {{ .Values.secrets.name }}

            - name: password.statusCheck.period.regular
              value: "{{ .Values.checkPeriod.regular }}"
            - name: password.statusCheck.period.intensive
              value: "{{ .Values.checkPeriod.intensive }}"
            - name: password.statusCheck.period.bufferInSeconds
              value: "{{ .Values.checkPeriod.bufferInSeconds }}"
            - name: singleconnect.agentName
              value: "{{ .Values.secrets.agentName }}"
            - name: singleconnect.encryptionKey
              value: "{{ .Values.secrets.encryptionKey }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
