apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secrets.name }}

type: {{ .Values.secrets.type }}

data:
   connection: {{ .Values.secrets.connection }} 
   installToken: {{ .Values.secrets.installToken  | b64enc }}
   address: {{ .Values.secrets.address  | b64enc }}

